### ISSUE TITLE
Jak mogę to uruchomić? Skompilować do dll - jak ?

### ISSUE THREAD

**Issue by MateuszKozak** [klukule/PaliaHook#3]
How can I run it? Compile to dll - how?

**Comment by sucrettae** [comment]
You need to install visual studio with the attached workload to compile it, then you can use an injector to inject the compiled dll into palia
![image](https://github.com/klukule/PaliaHook/assets/20794848/ab5e72fd-3729-447d-bd8b-2897ed737230)

**Comment by klukule** [comment]
Let me preface that this tool is not super useful without programming knowledge as it's a really basic tool and you need to know some stuff to keep it operating etc...

But anyways, as Estyms said, you'll need visual studio 2022 and cmake.
Using cmake you generate visual studio solution which you then build in the visual studio.
Afterwards you'll get the DLL which you still need to inject to the game, we do not provide an injector though.
